MAIN_FILE = TimeSide_SoundSoftware_2014_07# _G

pdf:
	echo ${MAIN_FILE}.tex
	pdflatex ${MAIN_FILE}.tex
	pdflatex ${MAIN_FILE}.tex

clean:

	rm -f *.aux *.bbl *.blg *.bst *.dvi *.idx *.lof *.log *.toc *.out  *.ind *.ilg *.nav *.snm *.vrb *~
