MAIN_FILE = slides_Parisson_Diadems_2014_02

pdf:
	echo ${MAIN_FILE}.tex
	pdflatex ${MAIN_FILE}.tex
	pdflatex ${MAIN_FILE}.tex

clean:

	rm -f *.aux *.bbl *.blg *.bst *.dvi *.idx *.lof *.log *.toc *.out  *.ind *.ilg *~
